In [17]:
import numpy as np

In [18]:
# Array Operations

In [3]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
a1

array([1, 2, 3, 4, 5])

In [22]:
# Arithmetic operations

In [4]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
a2

array([ 6,  7,  8,  9, 10])

In [5]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [9]:
a1 // a2

array([0, 0, 0, 0, 0])

In [19]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [21]:
# Broadcasting

In [11]:
l = [10,20,30,40,50]
arr = np.array(l)


In [12]:
arr + 10 

array([20, 30, 40, 50, 60])

In [13]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [23]:
# Deep and Shallow copy

In [24]:
a = np.arange(1.21)
a

array([0., 1.])

In [25]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
slice = a[0:5]
slice 

array([1, 2, 3, 4, 5])

In [27]:
slice = a[0:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a[4:5
]

array([5])

In [30]:
a[4:5]

array([5])

In [31]:
a[4:5] * 10

array([50])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a
b = a

In [34]:
b[0] = 99 
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a 
b = a.copy()

In [38]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
# Matrix operations

In [41]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5 ,6], [7, 8]])

In [42]:
A

array([[1, 2],
       [3, 4]])

In [43]:
B

array([[5, 6],
       [7, 8]])

In [46]:
# Matrix multiplication

In [44]:
A * B

array([[ 5, 12],
       [21, 32]])

In [45]:
A @ B

array([[19, 22],
       [43, 50]])

In [47]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [48]:
A

array([[1, 2],
       [3, 4]])

In [49]:
A.T

array([[1, 3],
       [2, 4]])

In [50]:
# Advance array manipulation

In [51]:
# Stacking arrays

In [52]:
A

array([[1, 2],
       [3, 4]])

In [53]:
B

array([[5, 6],
       [7, 8]])

In [54]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])


In [55]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [58]:
# Splitting arrays

In [59]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [61]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [63]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [64]:
for i in a:
    print(i)

1
2
3
4
