In [1]:
import numpy as np

In [ ]:
# numpy indexing in vector 

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6]

np.int64(17)

In [5]:
arr[9]

np.int64(20)

In [ ]:
# numpy slicing in vector

In [6]:
arr[1:4]

array([12, 13, 14])

In [7]:
arr[1:8]

array([12, 13, 14, 15, 16, 17, 18])

In [8]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[:7]

array([11, 12, 13, 14, 15, 16, 17])

In [11]:
arr[3::3]

array([14, 17, 20])

In [12]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [13]:
arr[4]

np.int64(15)

In [ ]:
# numpy indexing in matrix 

In [14]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[0,4]

np.int64(5)

In [16]:
arr[5,4]

np.int64(30)

In [ ]:
# numpy slicing in matrixa

In [17]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [18]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [19]:
arr[0:3,3:4]

array([[ 4],
       [ 9],
       [14]])

In [20]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [21]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [22]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [23]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# numpy Boolean_indexing

In [24]:
bool_index = arr %2 ==0

In [25]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [26]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])