In [1]:
import numpy as np

In [2]:
# Valid sudoku

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [5]:
b = np.sum(s,axis = 1)
b[b == 45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
b = np.sum(s,axis = 1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
b = np.sum(s, axis = 1)
for i in b:
    print(i) 

45
45
45
45
45
45
45
45
45


In [ ]:

for i in b:
    if i != 45:
        print("sudoku is not valid")
        break

    else:
        print("fb = np.sum(s, axis = 1)or rows it is valid")

for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid


In [10]:
c = np.sum(s, axis = 1)

In [12]:
c = np.sum(s,axis = 1)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break

    else:
        print("for columns it is valid")

for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid
for columns it is valid


In [13]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [14]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [17]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [18]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [16]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [20]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())


45
45
45
45
45
45
45
45
45


In [21]:
#General questions

In [22]:
import numpy as np

#Columns: [age, math marks, science marks]
data = np.array([
    [18, 85, 78],  # student 1
    [19, 97, 88],  # student 2
    [17, 69, 90],  # student 3
    [20, 88, 85],  # student 4
    [16, 75, 80]   # student 5
])

In [29]:
# get the shape of the matrix.
data.shape

(5, 3)

In [31]:
# find the average age of the students.
np.mean(data[:,0])

np.float64(18.0)

In [32]:
# extract the math marks of all students.
data[:,1]

array([85, 97, 69, 88, 75])

In [33]:
# find the highest science marks among the students.
np.max(data[:,2])

np.int64(90)

In [34]:
# get details of students who scored more than 90 in math.
data[data[:,1] > 90]

array([[19, 97, 88]])

In [36]:
# increase the math marks of all students by 5.
data[:,1] + 5


array([ 95, 107,  79,  98,  85])

In [37]:
# find how many students are younger than 19.
np.sum(data[:,0] < 19)

np.int64(3)

In [42]:
# calculate the average math marks of students (column-wise mean).
np.mean(data[:,1:],axis =0)

array([87.8, 84.2])

In [43]:
# get data of students who scored at least 80 in both the subjects.
data[(data[:,1] >= 80) & (data[:,2] >=80)]

array([[ 19, 102,  88],
       [ 20,  93,  85],
       [ 16,  80,  80]])

In [48]:
# replace all science marks less than < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[ 18,  90,  78],
       [ 19, 102,  88],
       [ 17,  74,  90],
       [ 20,  93,  85],
       [ 16,  80,  80]])