In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([1,2,3,4.6,"hello"])
arr

array(['1', '2', '3', '4.6', 'hello'], dtype='<U32')

In [6]:
l = [1,2,3],[4,5,6],[7,8,9]
l

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [7]:
np.array(l)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [3]:
import numpy as np

In [4]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [5]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [7]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [9]:
arr = np.linspace(1,10,4)
arr

array([ 1.,  4.,  7., 10.])

In [10]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [12]:
arr = np.linspace(1,0,100)
arr

array([1.        , 0.98989899, 0.97979798, 0.96969697, 0.95959596,
       0.94949495, 0.93939394, 0.92929293, 0.91919192, 0.90909091,
       0.8989899 , 0.88888889, 0.87878788, 0.86868687, 0.85858586,
       0.84848485, 0.83838384, 0.82828283, 0.81818182, 0.80808081,
       0.7979798 , 0.78787879, 0.77777778, 0.76767677, 0.75757576,
       0.74747475, 0.73737374, 0.72727273, 0.71717172, 0.70707071,
       0.6969697 , 0.68686869, 0.67676768, 0.66666667, 0.65656566,
       0.64646465, 0.63636364, 0.62626263, 0.61616162, 0.60606061,
       0.5959596 , 0.58585859, 0.57575758, 0.56565657, 0.55555556,
       0.54545455, 0.53535354, 0.52525253, 0.51515152, 0.50505051,
       0.49494949, 0.48484848, 0.47474747, 0.46464646, 0.45454545,
       0.44444444, 0.43434343, 0.42424242, 0.41414141, 0.4040404 ,
       0.39393939, 0.38383838, 0.37373737, 0.36363636, 0.35353535,
       0.34343434, 0.33333333, 0.32323232, 0.31313131, 0.3030303 ,
       0.29292929, 0.28282828, 0.27272727, 0.26262626, 0.25252

In [15]:
np.random.rand(10)


array([0.25874164, 0.02771194, 0.84209906, 0.76420633, 0.38293438,
       0.74420456, 0.59147975, 0.10777608, 0.42016928, 0.74957773])

In [16]:
np.random.randn(4)

array([0.60515455, 0.52063187, 0.60348965, 1.32694746])

In [17]:
np.random.randint(10,20,10)

array([17, 13, 18, 19, 14, 13, 12, 17, 17, 10], dtype=int32)

In [20]:
np.random.randint(10,20)

18

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

arr = np.shape(a)
print(arr)

(2, 3)


In [24]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

arr = np.size(a)
print(arr)

6


In [28]:
import numpy as np

arr = np.array([10, 20, 5, 30])
print(arr.min())      
   

5


In [29]:
import numpy as np

arr = np.array([10, 20, 5, 30])
print(arr.max())      
   

30


In [30]:
import numpy as np

arr = np.array([10, 20, 5, 30])
print(arr.sum())      
   

65


In [32]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.sum(arr, axis=1))

[ 6 15]


In [33]:
import numpy as np

arr = np.array([10, 20, 5, 30])
print(arr.mean())      
   

16.25
